core/urls.py
# Django
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
# Views users
from users.views import SignupView

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    # Login
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # Signup
    path('signup/', SignupView.as_view(), name='signup'),
    # Logout
    path('logout/', LogoutView.as_view(), name='logout'),
    # Home
    path('', login_required(TemplateView.as_view(template_name='home/index.html')), name='index'),
    # Programs
    path('bienestar/', include('wellness.urls'))
]

wellness/urls.py
# Django
from django.urls import path
# Views
from .views import *

urlpatterns = [
    path('actividades-culturales/', ProgramByCulturalActivitiesListView.as_view(), name='cultural-activities-list'),
    path('actividades-culturales/<slug:title>', ProgramDetailView.as_view(), name='program-cultural-detail'),
    path('actividades-deportivas/', ProgramBySportActivitiesListView.as_view(), name='sport-activities-list'),
    path('actividades-deportivas/<slug:slug>', ProgramDetailView.as_view(), name='program-sport-detail'),
    path('consulta-medica-y-enfermeria/', ProgramByMedicalAndNursingActivitiesListView.as_view(), name='medical-activities-list'),
    path('consulta-medica-y-enfermeria/<slug:title>', ProgramDetailView.as_view(), name='program-medical-detail'),
    path('semillitas/', ProgramByPolyLittleSeedSActivitiesListView.as_view(), name='seed-activities-list'),
    path('semillitas/<slug:title>', ProgramDetailView.as_view(), name='program-seed-detail'),
    path('enroll-user/<str:title>', enroll_user, name='enroll-user'),
    path('bienestar/<slug:slug>', ProgramDetailView.as_view(), name='program-detail'),
    path('inscriptions/', ProgramListView.as_view(), name='inscriptions'),
]

wellness/models.py
# Django
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Faculty(models.Model):
    """Model Faculty"""
    name = models.CharField(max_length=150, blank=False, null=False, verbose_name='Nombre de la facultad')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Facultad'
        verbose_name_plural = 'Facultades'


class Career(models.Model):
    """Model Career"""
    name = models.CharField(max_length=150, blank=False, null=False, verbose_name='Nombre de la carrera')
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, verbose_name='Facultad a la que pertenece la carrera')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Carrera'
        verbose_name_plural = 'Carreras'


class Program(models.Model):
    """Model Program"""
    ACTIVITY_IN_PROGRAM_CHOICES = [
        ('AC', 'ACTIVIDADES CULTURALES'),
        ('AD', 'ACTIVIDADES DEPORTIVAS'),
        ('CME', 'CONSULTA MÉDICA Y ENFERMERÍA'),
        ('SP', 'SEMILLITAS POLI'),
    ]
    name = models.CharField(max_length=100, blank=False, null=False, verbose_name='Nombre del programa')
    description = models.TextField(blank=False, null=False, verbose_name='Descripción del programa')
    capacity = models.PositiveIntegerField(verbose_name='Cupo del programa')
    current_capacity_available = models.PositiveIntegerField(blank=True, null=True, default=0, validators=[], verbose_name='Cupo actual disponible del programa')
    teacher = models.ForeignKey("users.Teacher", on_delete=models.CASCADE, verbose_name='Profesor asignado al programa')
    start_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True, verbose_name='Fecha inicio del programa')
    final_data = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True, verbose_name='Fecha inicio del programa')
    status = models.BooleanField(default=True, verbose_name='Estado del programa')
    image = models.URLField(default='sample.jpg', verbose_name='Ruta de la imagen del programa')
    activity = models.CharField(max_length=3, choices=ACTIVITY_IN_PROGRAM_CHOICES, blank=False, null=False, verbose_name='Actividad del programa')
    students = models.ManyToManyField("users.Student", blank=True, verbose_name='Estudiantes relacionado al programa')
    slug = models.SlugField(max_length=50, blank=True, null=True)

    def __str__(self):
        return "{} - Duración: {} hasta {} - Cupo actual: {} - Estudiantes: {}".format(self.name, self.start_date, self.final_data, self.current_capacity_available, self.students.count())

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Program, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Programa'
        verbose_name_plural = 'Programas'

    def get_absolute_url(self):
        return reverse("program_detail", kwargs={"slug": self.slug})


class Assistance(models.Model):
    """Model Assistance"""
    date_assistance = models.DateField(auto_now_add=True, auto_now=False, verbose_name='Fecha asistencia')
    program = models.ForeignKey(Program, on_delete=models.CASCADE, verbose_name='Programa de la asistencia')
    student = models.ForeignKey("users.Student", on_delete=models.CASCADE, verbose_name='Estudiante')

    def __str__(self):
        return "Asistencia: {} - Programa: {} - Estudiante: {}".format(self.date_assistance, self.program.name, self.student.get_full_name())

    class Meta:
        verbose_name = 'Asistencia'
        verbose_name_plural = 'Asistencias'


class Schedule(models.Model):
    """Model Schedule"""
    DAYS_OF_WEEK = (
        ('0', 'Domingo'),
        ('1', 'Lunes'),
        ('2', 'Martes'),
        ('3', 'Miercoles'),
        ('4', 'Jueves'),
        ('5', 'Viernes'),
        ('6', 'Sabado'),
    )
    day = models.CharField(max_length=3, blank=False, null=False, choices=DAYS_OF_WEEK, verbose_name='Día de la clase')
    start_time = models.TimeField(blank=False, null=False, verbose_name='Hora inicio clase')
    final_time = models.TimeField(blank=False, null=False, verbose_name='Hora final clase')
    program = models.ForeignKey(Program, on_delete=models.CASCADE, verbose_name='Programa de la clase')

    def __str__(self):
        return "Programa: {} - Día: {} {}/{} - ".format(self.program.name, self.day, self.start_time, self.final_time)

    class Meta:
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'

wellness/views.py
# Django
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
# Models
from .models import *
# Models User
from users.models import *

class ProgramByCulturalActivitiesListView(ListView):
    """Program By Cultural Activities List View"""
    model = Program
    queryset = Program.objects.filter(activity='AC')
    context_object_name = 'programs'
    template_name = 'wellness/programList.html'


class ProgramBySportActivitiesListView(ListView):
    """Programs By Sport Activities List View"""
    model = Program
    queryset = Program.objects.filter(activity='AD')
    context_object_name = 'programs'
    template_name = 'wellness/programList.html'


class ProgramByMedicalAndNursingActivitiesListView(ListView):
    """Programs By Medical and Nursing Consultation List View"""
    model = Program
    queryset = Program.objects.filter(activity='CME')
    context_object_name = 'programs'
    template_name = 'wellness/programList.html'


class ProgramByPolyLittleSeedSActivitiesListView(ListView):
    """Programs By Poli Little Seed List View"""
    model = Program
    queryset = Program.objects.filter(activity='SP')
    context_object_name = 'programs'
    template_name = 'wellness/programList.html'


class ProgramDetailView(DetailView):
    """Programs Detail View"""
    model = Program
    template_name = 'wellness/programDetail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    query_pk_and_slug = True

    def get_context_data(self, *args, **kwargs):
        context = super(ProgramDetailView, self).get_context_data(*args, **kwargs)
        instance = self.get_object()
        context['program'] = instance
        context['schedule'] = Schedule.objects.filter(program=instance).first()
        is_enroll = Program.objects.filter(students__user=self.request.user, slug=instance.slug).first()
        if is_enroll:
            context['is_enroll'] = True
        else:
            context['is_enroll'] = False
        return context

    def get_object(self, **kwargs):
        return Program.objects.get(slug=self.kwargs['slug'])


def enroll_user(request, title):
    """Inscribir a un estudiante a un programa"""
    if not Program.objects.filter(students__user=request.user, slug=title).first():
        program = Program.objects.get(slug=title)
        program.students.add(request.user.student)
        if program.current_capacity_available != 0:
            program.current_capacity_available -= 1
            program.save()
            messages.success(request, '¡Inscrito exitosamente!')
        else:
            messages.error(request, '¡Se ha alcanzado el maximo de cupo para este programa!')
    if program.activity == 'AC':
        return redirect('program-cultural-detail', program.slug)
    elif program.activity == 'AD':
        return redirect('program-sport-detail', program.slug)
    elif program.activity == 'CME':
        return redirect('program-medical-detail', program.slug)
    elif program.activity == 'SP':
        return redirect('program-seed-detail', program.slug)


class ProgramListView(ListView):
    """Programs List View"""
    model = Program
    context_object_name = 'programs'
    template_name = 'wellness/myInscriptions.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProgramListView, self).get_context_data(*args, **kwargs)
        context['programs'] = Program.objects.filter(students__user=self.request.user)
        return context

templates/wellness/myInscriptions.html
{% extends "layouts/base.html" %}

{% block title %} Mis Inscripciones  {% endblock %}

{% block content %}
    {% if programs %}
        <div class="row">
        {% for program in programs %}
                <div class="col-4">
                    <div class="card">
                        <img class="card-img-top img-fluid" src="{{ program.image }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-category">{{ program.get_activity_display }}</h5>
                            <h3 class="card-title">{{ program.name }}</h3>
                            <a href="{% url 'program-detail' program.slug %}" class="btn btn-primary float-right">¡Ver Detalle!</a>
                        </div>
                    </div>
                </div>
        {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-light" role="alert">
            Aún no te has inscrito a ningun programa...
        </div>
    {% endif %}
{% endblock content %}

templates/wellness/programDetail.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %} {{ program.name }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    <link href={% static 'assets/lib/main.css' %} rel='stylesheet'/>

{% endblock stylesheets %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {{ related }}
            <div class="card card-profile">
                <div class="card-body">
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.tags %}
                                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                                    {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <h6 class="card-category text-gray">{{ program.get_activity_display }} {% if is_enroll is False %}
                        <a href="{% url 'enroll-user' program.slug %}" class="btn btn-primary btn-round float-right">Confirmar
                            Inscripción</a>{% endif %}</h6>
                    <h4 class="card-title text-info">{{ program.name }}</h4>
                    <p class="card-text">{{ program.description }}</p>

                    <h4 class="card-title text-info">Fecha Inicio - Fecha Fin</h4>
                    <p class="card-text">{% if program.start_date is not None %}{{ program.start_date }}{% else %}No
                        disponible{% endif %}
                        <strong>hasta</strong>
                        {% if program.final_data is not None %}{{ program.final_data }}{% else %}Nodisponible{% endif %}
                    </p>
                    <h4 class="card-title text-info">Instructor</h4>
                    <p class="card-title">{{ program.teacher.user.get_full_name }}</p>
                    <h4 class="card-title text-info">Email</h4>
                    <p class="card-text"><strong class="text-info"></strong><a
                            href="mailto:{{ program.teacher.user.email }}">{{ program.teacher.user.email }}</a></p>
                    <h4 class="card-title text-info">Cupo Actual</h4>
                    <p class="card-text">{{ program.current_capacity_available }}/{{ program.capacity }}</p>
                    {% if schedule %}
                        <h4 class="card-title text-info">Horario</h4>
                        <div id='calendar'></div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script src={% static 'assets/lib/main.js' %}></script>
    <script src={% static 'assets/lib/locales/es.js' %}></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                defaultView: 'month',
                events: [{
                    title: '{{ program.name }}',
                    startRecur: '{{ program.start_date|date:"Y-m-d" }}',
                    endRecur: '{{ program.final_data|date:"Y-m-d" }}',
                    startTime: '{{ schedule.start_time }}',
                    endTime: '{{ schedule.final_time }}',
                    daysOfWeek: ['{{ schedule.day }}']
                }],
            });
            calendar.render();
        });

    </script>
{% endblock javascripts %}

templates/wellness/programList.html
{% extends "layouts/base.html" %}

{% block title %} Bienestar Universitario  {% endblock %}

{% block content %}
    {% if not programs %}
        <div class="alert alert-light" role="alert">
          Proximamente más programas...
        </div>
        <div></div>
    {% else %}
        <div class="row">
            {% for program in programs %}
                <div class="col-4">
                    <div class="card">
                        <img class="card-img-top img-fluid" src="{{ program.image }}" alt="Card image cap">
                          <div class="card-body">
                              <h5 class="card-category">{{ program.get_activity_display }}</h5>
                              <h3 class="card-title">{{ program.name }}</h3>
    {#                          <p class="card-text">{{ program.description }}</p>#}
    {#                          <p class="card-text"><strong class="text-info">Profesor: <br></strong>{{ program.teacher.user.get_full_name }}</p>#}
    {#                          <p class="card-text"><strong class="text-info">Email: <br></strong><a href="mailto:{{ program.teacher.user.email }}">{{ program.teacher.user.email }}</a></p>#}
                              <a href="{% url 'program-sport-detail' program.slug %}" class="btn btn-primary float-right">¡Inscribirme!</a>
                          </div>
                    </div>
                </div>
            {% endfor %}
    </div>
    {% endif %}
{% endblock content %}